/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.time.LocalDate;

public class App {

    public static void main(String[] args) {
        RentalAgency rentalAgency = new RentalAgency();

        Customer c1 = new Customer("Kofi", 43);
        Customer c2 = new Customer("Kwabena", 42);
        Customer c3 = new Customer("Helllo", 20);
        Customer c4 = new Customer("Kwesi", 44);

        Vehicle v1 = new Car("21", "Supra", 32, true);
        Vehicle v2 = new Car("22", "Corolla", 40, true);
        Vehicle v3 = new Motocycle("23", "Apsonic", 23);
        Vehicle v4 = new Truck("24", "Daf", 35);

        rentalAgency.addCustomer(c1);
        rentalAgency.addCustomer(c2);
        rentalAgency.addCustomer(c3);
        rentalAgency.addCustomer(c4);

        rentalAgency.addVehicle(v1);
        rentalAgency.addVehicle(v2);
        rentalAgency.addVehicle(v3);
        rentalAgency.addVehicle(v4);

        rentalAgency.viewVehicles();
        System.out.println();
        rentalAgency.viewCustomers();
        System.out.println();

        rentalAgency.processTransaction("Daf", "Kwabena", 3);
        System.out.println();
        rentalAgency.processTransaction("Supra", "Helllo", 2);
        System.out.println();
        rentalAgency.processTransaction("Corolla", "Kofi", 3);
        System.out.println();
        rentalAgency.processTransaction("Apsonic", "Kwesi", 2);
        System.out.println();
        rentalAgency.completeTransaction(1);
        System.out.println();
        rentalAgency.processTransaction("Daf", "Kofi", 3);

        System.out.println("===================Altered Transaction====================");
        rentalAgency.viewTransactions();

    }
}
